services:
  rocksdb-lab:
    build: .
    container_name: rocksdb-practice
    volumes:
      - ./rocksdb_data:/root/rocksdb_data
      - ./db_bench_log:/root/db_bench_log
    environment:
      - TARGET=${TARGET:-}
      - DB_BENCH_ARGS=${DB_BENCH_ARGS:-}
    restart: "no"